### ISSUE TITLE
Incubation process

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/audio-focus#26]
Hi @mounirlamouri and @rebeccahughes, was there a discourse thread for this incubation? I can't seem to find it. 

This repo seems to be missing some of the IPR templates, etc... which suggests it didn't go through the right channels to end up here. That's ok! but we should sort that out. 

Also, was this not in the purview of the Media WG? 

cc @WICG/chairs.

**Comment by mounirlamouri** [comment]
This work is part of the "Potential Normative Specification" of the [Media WG Charter](https://w3c.github.io/charter-media-wg/). I do not think it should move to the WG quite yet.

Regarding the discourse thread, this repo is fairly old and I believe it was created as a split from the Media Session work with some support from Apple. I do not remember if there was a thread to discuss the proposal at the time.

**Comment by marcoscaceres** [comment]
Thanks for the clarification. I'll add the IPR bits...

**Comment by marcoscaceres** [comment]
Hi @mounirlamouri, just checking how this is going and if you think it should move to the Media WG?

**Comment by mounirlamouri** [comment]
The status is the same as https://github.com/WICG/audio-focus/issues/26#issuecomment-517381834

**Comment by marcoscaceres** [comment]
Ok, cool. Thanks for the update.

**Comment by tidoust** [comment]
The Media Working Group recently adopted this proposal as recommendation track deliverable, and started to work on it in the [w3c/audio-session](https://github.com/w3c/audio-session). Closing this issue accordingly.
