### ISSUE TITLE
Is this still a thing?

### ISSUE THREAD

**Issue by hober** [WICG/audio-focus#28]
I think this is a promising idea and I'd love to see it progress. Is this still being worked on?

**Comment by mounirlamouri** [comment]
It's in scope of the Media WG but not something that is being worked on directly. Google isn't currently working on this and has no plans to do so in the near future but it's something that we would be happy to see progress.

**Comment by voxpelli** [comment]
I also think this is a promising specs and I have brought it up at occasions so I just want to link you into those discussions as they might be of interest:

I mentioned this in a Project Fugu request for #27: https://bugs.chromium.org/p/chromium/issues/detail?id=997514#c4

And this was also brought up in a Twitter discussion around that: https://twitter.com/voxpelli/status/1340601812655718401

**Comment by tidoust** [comment]
The Media Working Group recently adopted this proposal as recommendation track deliverable, and started to work on it in the [w3c/audio-session](https://github.com/w3c/audio-session). Closing this issue accordingly.

**Comment by schickling** [comment]
That's fantastic news. Thanks a lot for the update @tidoust 🎉
